POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Nurmikon leikkauksen abc",
    "author": "Kaarina Tuominen",
    "url": "nurmikonleikkaus.fi",
    "likes": 9385498
}