POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthcmlpbmEiLCJpZCI6IjY2OWFjMGNhYjEzNjRiZWQyNzdhNTNiNyIsImlhdCI6MTcyMTQyNDMzNn0.7r36pJilxEwBDvctStzMtLx0gj-wgQXT-BpTJbdFG4M

{
    "title": "Rapuja ja kossua",
    "author": "Kaarina Tuominen",
    "url": "rapujakossua.fi",
    "likes": 323242
}